version: "3.8"
services: 
    app:
        image: hnifrma/docker-laravel-str:8.42.1-1.0
        container_name: pos_untung-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes: 
            - ./:/var/www
        networks: 
            - default
    
    nginx:
        image: nginx:alpine
        container_name: pos_untung-nginx
        restart: unless-stopped
        ports: 
            - 8000:80
        volumes: 
            - ./:/var/www
            - ./config/nginx:/etc/nginx/conf.d/
        networks: 
            - default

networks: 
    default:
        external: true
        name: dbmain

